RAYT-5-Sphere
UwUClub/RAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAytracer pull request #30
Opened 2023-04-24 22:59 UTC by BaptisteLaran

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have documented my code
- [ ] Do we need to implement unit tests?

2023-04-25 06:58 UTC, Beafowl-Pull requested changes
bonne chance

2023-04-25 06:58 UTC, Beafowl-Pull commented on lib/Cylinder/Cylinder.cpp
> +    Cylinder::Cylinder(Color color, Point center, double radius, double height) : Primitives(color),
c'est pas bon, on attend une dataMap !

2023-04-25 06:58 UTC, Beafowl-Pull commented on lib/Cone/Cone.cpp
> +    Cone::Cone(Color color, Point center, double radius, double height) : Primitives(color),
c'est pas bon, on attend une dataMap !

2023-04-25 06:58 UTC, Beafowl-Pull commented on lib/Plane/Plane.cpp
> +    Plane::Plane(double pos, std::string axis, Color color) : Primitives(color)
c'est pas bon, on attend une dataMap !
de plus le Plane a deja etais fait sur la branche "RAYT-20"

2023-04-25 06:58 UTC, Beafowl-Pull commented on lib/Sphere/Api.cpp
> +    RayTracer::Entity::IEntity *createEntity(RayTracer::Point &aCenter, double aRadius, RayTracer::Entity::Color &aColor)
toujours pas

2023-04-25 06:58 UTC, Beafowl-Pull commented on lib/Plane/Api.cpp
> +    RayTracer::Entity::IEntity *createEntity(double aPos, std::string aAxis, RayTracer::Entity::Color &aColor)
nop

2023-04-25 06:58 UTC, Beafowl-Pull commented on lib/Cylinder/Api.cpp
> +    RayTracer::Entity::IEntity *createEntity(RayTracer::Entity::Color &aColor, RayTracer::Point &aCenter, double aRadius, double aHeight)
on attend une dataMap

2023-04-25 06:58 UTC, Beafowl-Pull commented on lib/Sphere/Sphere.cpp
> +    Sphere::Sphere(Point center, double radius, Color color) : Primitives(color),
c'est pas bon, on attend une dataMap !
de plus la Sphere a deja etais faite sur la branche "RAYT-20"

2023-04-25 06:58 UTC, Beafowl-Pull commented on src/Entity/Primitives/Primitives.cpp
> +    Primitives::Primitives(Color color) : Entity(EntityType::PRIMITIVE), _color(color)
c'est pas bon, on attend une dataMap !
de plus le Plane a deja etais fait sur la branche "RAYT-20"

2023-04-25 06:58 UTC, Beafowl-Pull commented on src/Entity/Primitives/Sphere/Sphere.cpp
> +/*
Pourquoi tu fait 2fois la meme chose exactement ?

2023-04-25 06:58 UTC, Beafowl-Pull commented on src/Entity/Primitives/Sphere/Sphere.hpp
> +/*
meme commentaire

2023-04-25 06:58 UTC, Beafowl-Pull commented on src/Utils/HitPoint.cpp
> +    HitPoint::HitPoint(double aX, double aY, double aZ, Entity::Color &aColor)
tu prend une dataMap

2023-04-25 06:58 UTC, Beafowl-Pull commented on src/Utils/HitPoint.hpp
> +#include "../../lib/Color/Color.hpp"
pas de path

2023-04-25 06:58 UTC, Beafowl-Pull commented on src/Utils/Ray.cpp
> +#include "../Entity/Primitives/Primitives.hpp"
pas de path

2023-04-25 06:58 UTC, Beafowl-Pull commented on src/Utils/Ray.hpp
> +#include "../../lib/Color/Color.hpp"
pas de path

2023-04-26 14:20 UTC, GlassAlo approved these changes

2023-04-26 14:21 UTC, GlassAlo approved these changes

2023-04-26 15:08 UTC, merged